CC = g++
CFLAGS = -g -Wall
TARGET = sliding_window2.o binary_search_tree13.o inheritance.o playlist3.o multiple_choice7.o challenge_1.o pipeline4.o

all: $(TARGET)

sliding_window2.o: sliding_window2.cpp
	$(CC) $(CFLAGS) -o $@ $^

playlist3.o: playlist3.cpp
	$(CC) $(CFLAGS) -o $@ $^

pipeline4.o: pipeline4.cpp
	$(CC) $(CFLAGS) -o $@ $^

binary_search_tree13.o: binary_search_tree13.cpp
	$(CC) $(CFLAGS) -o $@ $^

inheritance.o: inheritance.cpp
	$(CC) $(CFLAGS) -o $@ $^



multiple_choice.o: multiple_choice7.cpp
	$(CC) $(CFLAGS) -o $@ $^

challenge_1.o: challenge_1.cpp
	$(CC) $(CFLAGS) -o $@ $^



clean:
	rm -f $(TARGET)