CC = g++
CFLAGS = -g -Wall

all: q1_copy_bit q4_binary_tree_copy q6_function_caching 
q1_copy_bit: q1_copy_bit.cpp
	$(CC) $(CFLAGS) -o $@ $^

q4_binary_tree_copy: q4_binary_tree_copy.cpp
	$(CC) $(CFLAGS) -o $@ $^

q6_function_caching: q6_function_caching.cpp
	$(CC) $(CFLAGS) -o $@ $^