CC = gcc
CFLAGS = -g -Wall

all: reverse_bits change_endian shift_bits
reverse_bits: reverse_bits.c
	$(CC) $(CFLAGS) -o $@ $^

change_endian: change_endian.c
	$(CC) $(CFLAGS) -o $@ $^

shift_bits: shift_bits.c
	$(CC) $(CFLAGS) -o $@ $^