CC = g++
CFLAGS = -g -Wall

all: sliding_window binary_search_tree multiple_choice_test

sliding_window: sliding_window.cpp
	$(CC) $(CFLAGS) -o $@ $^

binary_search_tree: binary_search_tree.cpp
	$(CC) $(CFLAGS) -o $@ $^

multiple_choice_test: multiple_choice_test.cpp
	$(CC) $(CFLAGS) -o $@ $^