CC = g++
CFLAGS = -g -Wall

all: sliding_window binary_search_tree inheritance playlist multiple_choice

sliding_window: sliding_window.cpp
	$(CC) $(CFLAGS) -o $@ $^

binary_search_tree: binary_search_tree.cpp
	$(CC) $(CFLAGS) -o $@ $^

inheritance: inheritance.cpp
	$(CC) $(CFLAGS) -o $@ $^

playlist: playlist.cpp
	$(CC) $(CFLAGS) -o $@ $^

multiple_choice: multiple_choice.cpp
	$(CC) $(CFLAGS) -o $@ $^